version: 2
jobs:
  build:
    working_directory: ~/go/src/github.com/hyperledger-labs/minbft
    docker:
      - image: circleci/buildpack-deps:bionic-curl
    environment:
      GO_URL: https://dl.google.com/go/go1.11.4.linux-amd64.tar.gz
      SGX_SDK_URL: https://download.01.org/intel-sgx/linux-2.3.1/ubuntu18.04/sgx_linux_x64_sdk_2.3.101.46683.bin
      GOMETALINTER_URL: https://github.com/alecthomas/gometalinter/releases/download/v2.0.12/gometalinter-2.0.12-linux-amd64.tar.gz
      SGX_MODE: SIM
    steps:
      - run:
          name: Install Go
          command: |
            curl -s $GO_URL | sudo tar -xzf - -C /usr/local
            echo 'export GOPATH=$HOME/go' >> $BASH_ENV
            echo 'export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Intel SGX SDK
          command: |
            sudo apt-get -qq update
            sudo apt-get -qq install build-essential python pkg-config
            curl -s $SGX_SDK_URL -o sgx_linux_x64_sdk.bin
            chmod +x sgx_linux_x64_sdk.bin
            printf "no\n/opt/intel\n" | sudo ./sgx_linux_x64_sdk.bin
            rm sgx_linux_x64_sdk.bin
            echo ". /opt/intel/sgxsdk/environment" >> $BASH_ENV
      - run:
          name: Install gometalinter
          command: |
            curl -sL $GOMETALINTER_URL | sudo tar -xzf - --strip-components=1 -C /usr/local/bin
      - checkout
      - run:
          name: Test
          command: |
            make build check
      - run:
          name: Lint
          command: |
            make lint
workflows:
  version: 2
  build:
    jobs:
      - build
